# create an empty commit every day using cronjob

name: "Create an empty commit on a schedule"
on:
  push:
    branches-ignore: 
        - main #important for testing - so if I want to test the script I push it to a branch.
  schedule:
  - cron: "0 0 * * *"

jobs:
  commit:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: "main" #we just want to create our commits on main branch
          lfs: true
          fetch-depth: 0
          persist-credentials: false
          token: ${{secrets.PAT}} #If default token of automation user is used, no workflows for merge commit are triggered

      - name: Commit
        run: |
         Write-Output "set user config"
         git config --global user.name '${{secrets.GITNAME}}'
         git config --global user.email '${{secrets.GITEMAIL}}'
         Write-Output "setting remote state"
         git remote set-url origin https://x-access-token:${{secrets.PAT}}@github.com/${{ github.repository }}
         Write-Output "pull"
         git pull
         Write-Output "create commit"
         $date = Get-Date -format "yyyyMMdd HH:mm"
         git commit --allow-empty -m "$date A commit a day keeps the doctor away"
         Write-Output "pushing new commit"
         git push --force-with-lease